### ISSUE TITLE
The internet speed meter gnome isnt showing anything

### ISSUE THREAD

**Issue by TheSkynetDesigner29** [AlShakib/InternetSpeedMeter#10]
At first i installed the gnome from the gnome extension website but after i updated the fedora 36 via terminal, it suddenly doesnt show any internet speed and no it is not just this particular gnome but  also any other internet speed showing gnome.I will provide any information that u might need.I dont what to provide for this particular problem and please email me if u need any other relevent information. Thanks!

**Comment by AlShakib** [comment]
Did you update Internet Speed Meter to the latest version? Older version does not support Fedora 36...

**Comment by TheSkynetDesigner29** [comment]
> 

Yes, I even deleted the original file and downloaded the latest one.

**Comment by Addamo99** [comment]
Same problem here. Used to work like a charm on Fedora 36 until 1-2 weeks ago.

![Screenshot from 2022-10-18 22-28-26](https://user-images.githubusercontent.com/60587031/196548455-c2e70fe9-a35c-4531-b495-af00e4017729.png)

**Comment by ShrirajHegde** [comment]
Same problem, same timeline after an update

**Comment by ShrirajHegde** [comment]
@AlShakib Probably the format in `/proc/net/dev`. 

Here's a sample output.

```
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
    lo: 11129531   15210    0    0    0     0          0         0 11129531   15210    0    0    0     0       0          0
enp3s0:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
  wlo1: 2873608435 1954413    0    0    0     0          0         0 78861894  758243    0    0    0     0       0          0
virbr1:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
virbr0:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
virbr2:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
docker0:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0

```
Here's the file from `cat /proc/net/dev > temp`
[temp.gz](https://github.com/AlShakib/InternetSpeedMeter/files/9961940/temp.gz)

**Comment by AlShakib** [comment]
Thanks for the output. I'll try to update the extension as soon as possible. 👍

**Comment by ShrirajHegde** [comment]
Exception is triggered but log file isn't saved

**Comment by ShrirajHegde** [comment]
@AlShakib, it's actually the problem with GJS api. The new shell version seems to have broken something.

`      let dataStream = Gio.DataInputStream.new(fileStream);
`

This line throws an exception.

**Comment by ShrirajHegde** [comment]
https://github.com/AlShakib/InternetSpeedMeter/pull/13 Has a potential fix. Works fine for me. 

Method is taken from https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet, It should be backwards compatible.

**Comment by ShrirajHegde** [comment]
@TheSkynetDesigner29 @Addamo99 Try this fix

```
curl "https://raw.githubusercontent.com/ShrirajHegde/InternetSpeedMeter/master/src/extension.js" > ~/.local/share/gnome-shell/extensions/InternetSpeedMeter@alshakib.dev/extension.js
```

**Comment by AlShakib** [comment]
Submitted a new update to [Gnome Extensions](https://extensions.gnome.org/extension/2980/internet-speed-meter). Hopefully fixed with latest update.
