### ISSUE TITLE
units - kilo == 'k'

### ISSUE THREAD

**Issue by pwujek** [AlShakib/InternetSpeedMeter#3]
Please change the K in 'KB/s' to 'k' (lowercase) - uppercase K doesn't mean anything, lowercase k means 1000.

**Comment by AlShakib** [comment]
Sorry for the late reply. Anyway,  Kilobytes or Megabytes are actually based on 1024. The SI unit prefix KILO or MEGA means x1000. But computers use binary, so the closest whole binary number to that is 1024. Some people may prefer KiB or MiB for 1024 based units, but we think simple KB or MB is more readable.
