### ISSUE TITLE
Positioning in top bar is not consistent

### ISSUE THREAD

**Issue by ab1nn** [AlShakib/InternetSpeedMeter#7]
It moves other items in the top bar when the number of digits increases ( of the speed shown) (I have system tray extension and all, it moves left and right constantly due to changing net speed). So I tried moving it to left or center of the bar, but then it is changing position after the PC come backs from sleep or lock screen (Goes to the left most position). Please fix.

Before
![image](https://user-images.githubusercontent.com/63762448/141041411-746754e8-9847-47df-9e2d-69e53e289c66.png)

After lock screen or sleep
![image](https://user-images.githubusercontent.com/63762448/141041474-ee426dd0-5921-46aa-9e94-8a0d81310c53.png)

**Comment by AlShakib** [comment]
Gnome shell version?
Extension version?

**Comment by ab1nn** [comment]
Sorry to bother you, but I just updated to gnome shell 41.1 and extension 9 today and now its all fine. Very sorry. But this had been a problem for me till yesterday.
I used to have gnome 40 and extension version 8.
